GET http://localhost:8080/api/employees/

###
GET http://localhost:8080/robert/

###
POST http://localhost:8080/api/employees/
Content-Type: application/json

{
  "name": "Valaki",
  "level": "Godlike",
  "position": "Joker"
}

###
DELETE http://localhost:8080/api/employees/637e22ce74045fd928489109

###
PATCH http://localhost:8080/api/employees/637e22ce74045fd928489109
Content-Type:  application/json

{
  "name": "Adam"
}

###
GET http://localhost:8080/api/trainings/

###
POST http://localhost:8080/api/trainings/
Content-Type: application/json

{
  "title": "test",
  "difficulty": "test"
}

###
GET http://localhost:8080/divisions/

###
POST http://localhost:8080/divisions/
Content-Type: application/json

{
  "name": "PR",
  "boss": "63dfc344418bdbdf47331d65",
  "budget": 500000,
  "location": { "city": "London", "country": "UK" },
  "employees": ["63dfc344418bdbdf47331d65"]
}

###
DELETE http://localhost:8080/divisions/63e0d4af5655364124f8b666

###
PATCH http://localhost:8080/divisions/63e0d4af5655364124f8b666
Content-Type:  application/json

{
  "employees": ["63dfc344418bdbdf47331d65", "63dfc344418bdbdf47331d63", "63dfc344418bdbdf47331d5d"]
}
